#!/bin/bash
# script config:

# verbosities
# 0 error
# 1 info
# 2 debug
verbosity="2"

configdir="$scriptprefix/configs/defaults/"

# install config:
distro="archlinux"
machinename="archlinux"

fde="0"

declare -A mountdev
declare -A mounttype
declare -A mountopts

btrfssubvol="sys/$machinename"

mountdev["/"]="" # /dev/loop0p1
mounttype["/"]="btrfs"
mountopts["/"]="subvol=$btrfssubvol,compress=zstd:0"

mountdev["/boot/efi"]="" # /dev/loop0p2
mounttype["/boot/efi"]="vfat"
mountopts["/boot/efi"]="defaults"

bios_dev="" # /dev/loop0

username="" # user

# scripts/packages:
container_scripts="locale pacman sudo user-account"
user_container_scripts="paru \
dracut nvidia \
packages networkmanager sddm \
bash_profile tmux htop systemd vaapi fcitx5 gtk pip flatpak flatpak-breeze-dark"
arch_chroot_scripts="fstab grub"

	unset pkgs
	declare -A pkgs

	# system
	pkgs[linux]="linux-zen linux-zen-headers linux-firmware dracut"
	pkgs[grub]="efibootmgr os-prober grub"
	
	pkgs[system]="sudo networkmanager util-linux"
	pkgs[utils]="nano vi tmux htop nvtop arch-install-scripts base-devel man-db p7zip openssh rsync wget curl aria2 iputils"
	pkgs[disk]="gptfdisk btrfs-progs exfatprogs e2fsprogs dosfstools ntfs-3g"
	# pkgs[disk_extra]="f2fs-tools hfsprogs jfsutils reiserfsprogs xfsprogs xfsdump mtools nilfs-utils cryptsetup lvm2 udftools"
	# pkgs[utils_extra]="traceroute"
	pkgs[other]="python"
	pkgs[packagemanagers]="packagekit-qt5"

	# cpu
	pkgs[intel_cpu]="intel-ucode"
	pkgs[amd_cpu]="amd-ucode"

	# gpu
	pkgs[intel_gpu]="libva-intel-driver intel-gpu-tools"
	pkgs[nvidia_gpu]="nvidia-dkms"
	pkgs[amd_gpu]="libva-mesa-driver vulkan-radeon amdvlk mesa-vdpau radeontop"
	pkgs[vaapi]="libva libva-utils libvdpau-va-gl"
	pkgs[vdpau]="libva-vdpau-driver vdpauinfo"

	# desktop
	pkgs[fonts]="noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra"

	pipewire_pkgs="pipewire pipewire-alsa pipewire-jack pipewire-pulse gst-plugin-pipewire wireplumber"
	desktop_portals="xdg-desktop-portal-kde xdg-desktop-portal-gtk xdg-desktop-portal-gnome xdg-desktop-portal"
	pkgs[desktop_base]="wayland $pipewire_pkgs $desktop_portals"
	pkgs[fcitx5]="fcitx5 fcitx5-qt fcitx5-gtk fcitx5-configtool fcitx5-hangul fcitx5-mozc"

	pkgs[phonon]="phonon-qt5-vlc phonon-qt5-gstreamer gst-libav gst-plugins-good gst-plugins-ugly gst-plugins-bad gstreamer-vaapi"
	pkgs[kde_plasma]="plasma-meta plasma sddm plasma-wayland-session"
	pkgs[kde_apps]="konsole dolphin kate spectacle plasma-systemmonitor ksysguard ark kwalletmanager"
	# pkgs[kde_apps_extra]="filelight partitionmanager gwenview"

	pkgs[etc_apps]="flatpak gparted aur/firefox-nightly aur/protonvpn-gui aur/cloudflare-warp-bin"

	pkgs[c_devel]="gcc clang make cmake git gdb lldb"
	pkgs[vscode]="aur/visual-studio-code-bin gnome-keyring"
	pkgs[obs]="obs-studio v4l2loopback-dkms"
pkglist="${pkgs[@]}"

# libva-nvidia-driver asusctl supergfxctl
flatpak_pkglist="org.gtk.Gtk3theme.Breeze-Dark"
pip_pkglist="yt-dlp konsave"
# flatpak_pkglist="$flatpak_pkglist com.github.tchx84.Flatseal org.mozilla.firefox com.usebottles.bottles"
