#!/bin/bash
createuser()
{
	if [ $(compgen -u | grep -c "${username}") -eq 0 ]; then
		useradd -m ${username}
	fi

	usermod -aG wheel ${username}
	passwd -d ${username}
}
createuser_systemd_homed()
{
	systemctl enable --now systemd-homed.service
	homectl create "${username}" --member-of="wheel" --storage=directory --fs-type=btrfs
	# --storage=directory --shell="/usr/bin/zsh"
	passwd -d ${username}
	# homectl update --shell="/usr/bin/zsh"
}
