#!/bin/bash

install()
{
	# https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US
	# https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=linux64&lang=en-US
	# https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US
	# https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US

	# https://support.mozilla.org/en-US/kb/install-firefox-linux
	wget -c "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US" -O - | tar -xjf -

	mkdir -p /opt
	mv firefox /opt

	mkdir -p /usr/local/bin
	ln -s /opt/firefox/firefox /usr/local/bin/firefox

	mkdir -p /usr/local/share/applications
	wget https://raw.githubusercontent.com/mozilla/sumo-kb/main/install-firefox-linux/firefox.desktop -P /usr/local/share/applications
}
# MOZ_ENABLE_WAYLAND=1 MOZ_DISABLE_RDD_SANDBOX=1
# layout.css.visited_links_enabled
