#!/bin/bash
tee $HOME/.bash_profile.d/wayland.sh << 'EOF' > /dev/null
#!/bin/bash
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    export CLUTTER_BACKEND=wayland
    export SDL_VIDEODRIVER=wayland
fi
EOF
source $HOME/.bash_profile