#!/bin/bash
log "info" "Installing and configuring dracut"
run_commands "systemd-nspawn" "${username}" <<- ENDOFSCRIPT
keypath="${keypath}"
passphrase="${passphrase}"
$(cat "${scriptdir}/script")
install
compress
ENDOFSCRIPT

if [ use_disk_encryption -eq 1 ]; then
	log "info" "Generating keyfile and configuring dracut to embed it in initramfs"
	run_commands "arch-chroot" "root" <<- ENDOFSCRIPT
	keypath="${keypath}"
	passphrase="${passphrase}"
	crypt_dev="${crypt_dev}"
	$(cat "${scriptdir}/script")
	crypt
	keyfile
	ENDOFSCRIPT
fi