#!/bin/bash
# run as: root
# depends: dracut
paru -Sy --needed --noconfirm dracut aur/dracut-hook
sudo mkdir -p /etc/dracut.conf.d
sudo tee /etc/dracut.conf.d/compress.conf << 'EOF' > /dev/null
compress="zstd"
EOF
