#!/bin/bash
createuser()
{
	if [ $(compgen -u | grep -c "${username}") -eq 0 ]; then
		useradd ${username}
	fi

	usermod -aG wheel ${username}
	passwd -d ${username}
	passwd -d $username
	# usermod -aG wheel $username
}
createuser
