#!/bin/bash
sudo sysctl kernel.unprivileged_userns_clone=1
sudo touch /etc/subuid /etc/subgid
sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 "${USER}"

# sudo mkdir -p /etc/systemd/system/user@.service.d
# cat <<EOF | sudo tee /etc/systemd/system/user@.service.d/delegate.conf
# [Service]
# Delegate=cpu cpuset io memory pids
# EOF
# sudo systemctl daemon-reload
