#!/bin/bash
generatelocale()
{
	if [ -f /etc/locale.gen.backup ]
	then
		return
	fi
	mv /etc/locale.gen /etc/locale.gen.backup
	tee /etc/locale.gen <<- 'EOF' > /dev/null
	en_US.UTF-8 UTF-8
	EOF
	locale-gen
	localectl set-locale LANG=en_US.UTF-8
	unset LANG
	source /etc/profile.d/locale.sh
}
generatelocale