#!/bin/bash
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
sudo flatpak remote-add --if-not-exists kdeapps https://distribute.kde.org/kdeapps.flatpakrepo
sudo flatpak install -y $flatpak_pkglist
# sudo flatpak override --env=LIBVA_DRIVER_NAME=i965