#!/bin/bash
log "info" "Installing and configuring grub"
run_commands "arch-chroot" "root" <<- ENDOFSCRIPT
${default_config_contents}
${config_contents}
# mountdev=${mountdev}
# mounttype=${mounttype}
# mountopts=${mountopts}
use_disk_encryption=${use_disk_encryption}
keypath=${keypath}
crypt_dev=${crypt_dev}
machinename=${machinename}
bios_dev=${bios_dev}
$(cat "${scriptdir}/script")
ENDOFSCRIPT