#!/bin/bash
# run as root

install_grub()
{
	if [ ! -f /boot/efi/EFI/Boot/boot*.efi ]; then
		removable="--removable"
	fi
	
	if [ -e "${mountdev[/boot/efi]}" ]; then
		grub-install --target="x86_64-efi" --efi-directory=/boot/efi --boot-directory=/boot/efi/EFI --bootloader-id="GRUB" $removable --no-nvram --force
	fi
	if [ -e "$bios_dev" ]; then
		grub-install --target="i386-pc" --boot-directory=/boot/efi/EFI "$bios_dev" --force
	fi
	# i386-coreboot
}

configure_grub_defaults()
{
	if [ -f "/etc/default/grub.backup" ]; then
		rm "/etc/default/grub"
		mv "/etc/default/grub.backup" "/etc/default/grub"
	fi
	cp "/etc/default/grub" "/etc/default/grub.backup"
	tee -a /etc/default/grub <<- EOF > /dev/null
	GRUB_DISTRIBUTOR="$machinename"
	GRUB_PRELOAD_MODULES+=" part_gpt part_msdos "
	EOF
}

configure_grub_luks1()
{
	tee -a /etc/default/grub <<- "EOF" > /dev/null
	GRUB_CMDLINE_LINUX_DEFAULT+=" rd.luks=1 "
	GRUB_PRELOAD_MODULES+=" luks "
	GRUB_ENABLE_CRYPTODISK=y
	EOF
}

configure_grub_luks_keyfile()
{
	tee -a /etc/default/grub <<- EOF > /dev/null
	GRUB_CMDLINE_LINUX_DEFAULT+=" rd.luks.key=${keypath} rd.luks.uuid=luks-$(cryptsetup luksUUID "${crypt_dev}") "
	EOF
}

configure_grub_luks2()
{
	tee -a "/etc/default/grub" <<- 'EOF' > /dev/null
	GRUB_CMDLINE_LINUX+=" rd.luks=1 "
	GRUB_PRELOAD_MODULES+=" luks2 "
	GRUB_ENABLE_CRYPTODISK=y
	EOF

	sudo tee -a "/etc/grub.d/01_crypt" <<- EOF > /dev/null
	#!/bin/sh
	echo "cryptomount -u $(cryptsetup luksUUID "${crypt_dev}" | tr -d -)"
	EOF

	chmod +x "/etc/grub.d/01_crypt"
}

run_grub_mkconfig()
{
	grub-mkconfig -o /boot/efi/EFI/grub/grub.cfg
}

postinstall()
{
	configure_grub_defaults
	if [ ${use_disk_encryption} -eq 1 ]; then
		configure_grub_${crypt_type}
		configure_grub_luks_keyfile
	fi
	install_grub
	run_grub_mkconfig
}
postinstall
