#!/bin/bash
python -m ensurepip --upgrade
python -m pip install --upgrade pip
tee "$HOME/.bash_profile.d/pip.sh" << 'EOF' > /dev/null
append_path "$HOME/.local/bin"
EOF
source "$HOME/.bash_profile"
# python -m pip install --upgrade pip
