#!/bin/bash
log "info" "Generating fstab"
run_commands "arch-chroot" "root" <<- ENDOFSCRIPT
mounts_points=(${mounts_points[@]})
mounts_devices=(${mounts_devices[@]})
mounts_types=(${mounts_types[@]})
mounts_opts=(${mounts_opts[@]})

$(cat "${scriptdir}/script")
ENDOFSCRIPT