#!/bin/bash
tee $HOME/.bash_profile.d/vaapi.sh << 'EOF' > /dev/null
export LIBVA_DRIVERS_PATH=/usr/lib/dri
# export LIBVA_DRIVER_NAME=
printf "%s\n" "\$LIBVA_DRIVER_NAME is not set;"
printf "%s\n" "you can set it from \$HOME/.bash_profile.d/vaapi.sh"
EOF
source $HOME/.bash_profile
