#!/bin/bash
# https://docs.docker.com/engine/security/rootless/
paru -Sy --needed --noconfirm fuse-overlayfs

## rootless
curl -fsSL https://get.docker.com/rootless | sh
systemctl --user daemon-reload
systemctl --user enable --now docker