#!/bin/bash
# pacman -S --needed --noconfirm paru
sudo pacman -Sy --needed --noconfirm base-devel git
mkdir -p /tmp/clone
cd /tmp/clone
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si --noconfirm